spring:
  application:
    name: alex_admin
  profiles:
    active: dev

  redis:
    host: localhost #redis服务地址
    port: 6379      #redis端口号
    database: 0     #redis默认数据库索引
    timeout: 180000 #redis连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20     #连接池最大连接数
        max-await: -1      #最大阻塞等待时间（负数表示没有限制）
        max-idle: 5        #连接池中最大的空闲连接数
        min-idle: 0        #连接池中最小的空闲连接数
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


isRememberMeExpiresSecond: 259200000 #记住密码三天
tokenHead: bearer_

audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: mogublog
  expiresSecond: 3600000  #1个小时 3600
  refreshSecond: 3600

tokenHeader: Authorization

logging:
  level:
    com.alex.blog.xo.mapper: debug
