spring:
  application:
    name: alex_admin
  profiles:
    active: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


isRememberMeExpiresSecond: 259200000 #记住密码三天
tokenHead: bearer_

audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: mogublog
  expiresSecond: 3600000  #1个小时 3600
  refreshSecond: 3600

tokenHeader: Authorization

logging:
  level:
    com.alex.blog.xo.mapper: debug
