spring:
  application:
    name: alex-admin
  profiles:
    active: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


isRememberMeExpiresSecond: 259200000 #记住密码三天
tokenHead: bearer_

audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: mogublog
  expiresSecond: 3600000  #1个小时 3600
  refreshSecond: 3600

tokenHeader: Authorization

logging:
  level:
    com.alex.blog.xo.mapper: debug

#将来单独拿出来生成一个yaml
data:
  web:
    project_name: alex博客
    project_name_en: alex_blog
    logo: https://gitee.com/moxi159753/mogu_blog_v2/raw/Nacos/doc/images/gitee/favicon2.ico
  website:
    url: http://192.168.177.140:9527/#/
