server:
  port: 30088

spring:
  application:
    name: alex-miaosha

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false
    username: root
    data-password: mysql

logging:
  level:
    com.alex.blog.miaosha.xo.mapper: debug
