server:
  port: 88
spring:
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建的路由功能，利用微服务进行路由
      routes:
        - id: alex_admin
          uri: lb://alex_admin
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<segment>.*),/$\{segment}
        - id: alex_search
            uri: lb://alex_search
            predicates:
              - Path=/search/**
            filters:
              - RewritePath=/search/(?<segment>.*),/$\{segment}
        - id: alex_picture
            uri: lb://alex_picture
            predicates:
              - Path=/picture/**
            filters:
              - RewritePath=/picture/(?<segment>.*),/$\{segment}