server:
  port: 88
spring:
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: alex_user
          uri: lb://alex_user
          predicates:
            - Path=/adminInfo/auth/**
          filters:
            - RewritePath=/adminInfo/(?<segment>.*),/$\{segment}